// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthResponse struct {
	User        *User  `json:"user"`
	AccessToken string `json:"accessToken"`
}

type CreatePostInput struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

type GoogleLoginInput struct {
	Code string `json:"code"`
}

type Mutation struct {
}

type PaginatedPosts struct {
	Posts       []*Post `json:"posts"`
	TotalCount  int     `json:"totalCount"`
	HasNextPage bool    `json:"hasNextPage"`
}

type Post struct {
	ID        string `json:"id"`
	Title     string `json:"title"`
	Content   string `json:"content"`
	UserID    string `json:"userId"`
	CreatedAt string `json:"createdAt"`
}

type Query struct {
}

type RefreshResponse struct {
	AccessToken string `json:"accessToken"`
	User        *User  `json:"user"`
}

type UpdatePostInput struct {
	ID      string `json:"id"`
	Title   string `json:"title"`
	Content string `json:"content"`
}

type User struct {
	ID           string `json:"id"`
	FirstName    string `json:"firstName"`
	LastName     string `json:"lastName"`
	Email        string `json:"email"`
	ProfilePhoto string `json:"profilePhoto"`
}
